### ISSUE TITLE
Clarify status of gem in Rails 4.1+

### ISSUE THREAD

**Issue by iangreenleaf** [iangreenleaf/activerecord_enum#7]
The introduction of psuedo-enum support in 4.1 calls for some clarification of what role this gem should play.

I think the core purpose of this gem is still valuable, since Active Record's stuff seems aimed at integer columns, not actual ENUMs. So it seems that it should stick around and not be dropped entirely. But I should add a section to the README that explains this for people who might be confused.

I might also need to consider changing to name to reduce confusion.

**Comment by dtakahas** [comment]
> So it seems that it should stick around and not be dropped entirely.

I know this is a late reply, but I wanted to chime in to agree with you here. The use of actual ENUMs is a valuable thing!

**Comment by iangreenleaf** [comment]
Well, good news, #8 just landed with support for 4.2! I haven't updated the README yet, though.
